Update new_version_check.yml

diff --git a/.github/workflows/new_version_check.yml b/.github/workflows/new_version_check.yml
--- a/.github/workflows/new_version_check.yml
+++ b/.github/workflows/new_version_check.yml
@@ -47,25 +47,20 @@ jobs:
         shell: bash {0}
         run: |
           echo "${{ steps.latest-version.outputs.version }}" > chromium_version.txt
-          #set +e
-          #ulimit -a
-          #sudo ulimit -Sn 65536
-          #ulimit -Sp 9999999
-          #ulimit -a
-          #exit
           mkdir -p build/download_cache
           ./utils/downloads.py retrieve -i downloads.ini -c build/download_cache
           ./utils/downloads.py unpack -i downloads.ini -c build/download_cache build/src
-          #./devutils/update_lists.py -t build/src
+          ./devutils/update_lists.py -t build/src
           source devutils/set_quilt_vars.sh
-          #export QUILT_PAGER="less -FRX"
-          #env
           cd build/src
           sudo quilt push -a --refresh -v
           export RETVAL=$?
           echo -n "::set-output name=retval::$RETVAL"
           if [ $RETVAL -gt 0 ]; then echo "quilt push FAILED"; exit 0; fi;
           sudo quilt pop -a -v
+          export RETVAL=$?
+          echo -n "::set-output name=retval::$RETVAL"
+          if [ $RETVAL -gt 0 ]; then echo "quilt pop FAILED"; exit 0; fi;
           cd ../..
           devutils/validate_config.py
           export RETVAL=$?
